List<Map<String, dynamic>> NADATA = [
  one,
  two,
  three,
  four,
  five,
  six,
];

Map<String, dynamic> one = {
  "NA": 79,
  "Candidates": [
    "Muhammad Akram",
    "Asjad Hussain",
    "Babar Maqbool Qazi",
    "Ch. Adil Buksh Chattha",
    "Johar Sarwar Cheema",
    "Malik Abdul Rehman Sadi",
    "Miraj Din",
    "Muhammad Amin",
    "Muhammad Arshad",
    "Muhammad Umer Usman",
    "Nisar Ahmed Cheema",
    "Ch. Ijaz Ahmed Cheema",
    "Mohammed Ahmed Chattha",
    "Muhammad Fayyaz"
  ],
  "Party": [
    "AOAT",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "PMLN",
    "PPPP",
    "PTI",
    "TLP"
  ],
  "Areas": [
    "ABUL FATEH WALI",
    "ADIL GARH",
    "AHMAD NAGAR",
    "AJAN CHAK",
    "AJITKE",
    "ALI PUR CH ATHA",
    "ARAINAN WALA",
    "ARAZI AZIZ CHAK",
    "AULAKH",
    "AZIZ CHAK",
    "BAGARIAN KOHNA",
    "BAGARIAN NAU",
    "BAKHSH",
    "BANGWAN",
    "BARA PIND",
    "BARIAR",
    "BEANKA CHEEMA",
    "BEEGHA",
    "BEHRAM",
    "BHAGHAT GARH",
    "BHAGWAN PURA",
    "BHAROKI CHEEMA",
    "BHATTI KE",
    "BHATTI MANSUR",
    "BHUMAN BATH",
    "BUCHA CHATHA",
    "BUDHA RAJADA",
    "BURE WALI",
    "BURJ CHEEMA",
    "BURJ DHALLA",
    "BURJ MANCHAR",
    "BURJ RATTA",
    "BURJ TASHA",
    "CHABBA CHEEMA",
    "CHAHARKE",
    "Chak ALI SHER",
    "CHAK AROOP CHAND",
    "CHAK BEG",
    "CHAK DADAN",
    "CHAK GILLAN",
    "CHAK KOTOHAR CHAK",
    "CHAK MAHI",
    "CHAK MARDA",
    "CHAK PATHAN",
    "CHAK SADA",
    "CHAK SAN",
    "CHAK SANATTA",
    "CHAK SATIA",
    "CHANGAN WALI",
    "CHAR YARI (HUSSAIN PURA)",
    "CHAURA",
    "CHHANI JAWALA",
    "CHHANI JUMMA",
    "CHHANI LAK",
    "CHHANI MAHARAM",
    "CHHANI MOTI",
    "CHHANI MURID",
    "CHHANI NATHU",
    "CHHANI WALI Dad",
    "CHHANWAN",
    "CHOWATIAN (JALALPUR CHATAH)",
    "DAD WALI",
    "DARGHI WALA",
    "DARVAISH KEY",
    "DHAB CHEEMA",
    "DHALLA CHATHA",
    "DHAPAI AMIR SINGH",
    "DHAPAI HASANWALI",
    "DHAPAI MEHTAB SINGH",
    "DHARAM KOT",
    "DHARAN DIAN",
    "DHARO WAL",
    "DHIL",
    "DHILWAN",
    "DHIPPA",
    "DHONEKE",
    "DHONKAL T.C. (MOH. AUTAR)",
    "DILAWAR CHEEMA",
    "DIWAN KOT",
    "DODHAN WALI KALAN",
    "FAQIRAN WALI KALAN",
    "FAQIRANWALI",
    "FARM JHAKANWALI",
    "FATEH GARH",
    "FATEH PUR",
    "GAJAR GOLA",
    "GARAP GARH",
    "GARHI GHULLAH",
    "GHAKKE MEETER NEAR Masjid FAROOQIA",
    "GHAKKHAR M.C.( MOH. BANGLA ABADI )",
    "GHARI DOGGAR",
    "GHARI JALLA",
    "GHHIA WALA",
    "GILL WALA",
    "GUNIAN WALA",
    "GURALI",
    "HAIRAN WALA KALAN",
    "HAIRAN WALA KHURD",
    "HARCHO KI",
    "HARDO JIOKA",
    "HARDO PANDOKE",
    "HARDO WARPAL",
    "HARI PUR",
    "HASSAN WALI",
    "HAZRAT KAILIANWALA",
    "IBBAN WALI",
    "ISMIAL PURA",
    "JAGNA",
    "JAMKE CHATHA",
    "JANDAN WALA",
    "JANDIALA DHABWALA",
    "JATI SHAH REHMAN",
    "JAURA",
    "JAURA JANUBI GHARBI",
    "JAURA SHARQI",
    "JHAM WALA",
    "JHATAN WALI",
    "JOKHIAN",
    "Jueney Wali",
    "JURAI",
    "KAHN GARH",
    "KAKKA KAULU",
    "KALAIR",
    "KALASKI",
    "KALE WALA",
    "KALER",
    "KALU CHEEMA",
    "KALU WALI",
    "KARTAR PUR KALAN",
    "KARTAR PUR KHURD",
    "Kathor Kalan",
    "KHANKI",
    "KHASRA",
    "Khewey Wali",
    "KHOJIAN WALA",
    "KHOSAR",
    "KHURD",
    "KOLAR",
    "KOT BANGASH",
    "KOT BELA",
    "KOT BHAGA",
    "KOT DEWAL",
    "KOT FAZLA",
    "KOT HAR KIRAN",
    "KOT HARA",
    "KOT IMAM",
    "KOT IMAM BAKHSH",
    "KOT INAYAT KHAN",
    "KOT JAFAR",
    "KOT JAHANGIR",
    "KOT KAHL",
    "KOT KHIZRI",
    "KOT MEHAR Ali",
    "KOT MIRAN",
    "KOT NATHU",
    "KOT NAWAN",
    "KOT NURA",
    "KOT PAROYA",
    "KOT QADIR BAKHSH",
    "KOT QAZI",
    "KOT RATTA",
    "KOT SAIDAN",
    "KOT SHAH MUHAMMAD",
    "KOT WARAS",
    "KOT YOUSAF",
    "KOTLA PIRAN",
    "KOTLI ISA",
    "KOTLI KAHLWAN",
    "KOTLI MANGU",
    "KOTLI MIANI",
    "KOTLI SAHIAN (KOTLI KHUSHI MUHAMMAD)",
    "LADHEWALA",
    "LANGIAN WALI",
    "LAWARI WALA",
    "LUND PUR (RAMKE)",
    "MADAN CHAK",
    "MADRSA",
    "MAHAD PUR",
    "MAHARAJ KE",
    "MALAN WALI",
    "MALSI PURA",
    "MANCHAR CHATHA",
    "MANDIALA CHATHA",
    "MANEWALA",
    "MANGA",
    "MANSUR WALI",
    "MARDEKE MANZOORABAD",
    "MARUFABAD",
    "MATWAN",
    "MOHALANKE",
    "NADALA PAKKA",
    "NAHARKE",
    "NAIWALA",
    "NAT",
    "NAT KALAN",
    "NAT KALAN KUMHARAN WALA CHURCH",
    "NAT KALAN MOH. PIR QAMAR SHAH",
    "NAT KALAN MOH. TIBBA WALA",
    "NIHALU CHAK",
    "NOIAN WALA",
    "NUR PUR",
    "OJLA KALAN",
    "OJLA KHURD",
    "PATHAN WALI",
    "PATHANKI",
    "PATOKE",
    "PHALOKE",
    "PHEROKE",
    "PINDORI KALAN",
    "PINDORI KHURD",
    "PIR KOT",
    "PUNJGARAIN",
    "QILA BAGH SINGH",
    "QILA SANGIAN",
    "RAJAB CHAK",
    "RAKH",
    "RAKH BHAROKI",
    "RAKH SANT PURA",
    "RAKH SINGHPURA",
    "RAM GARH",
    "RAM PURA",
    "RANAN",
    "RANIKI",
    "RANSI WALI",
    "RASOOL NAGAR",
    "RATTI",
    "RODALA",
    "RUKAN PUR",
    "SADHANWALA",
    "SAHDAN WALI",
    "SAID NAGAR",
    "SAIDE WALI",
    "SAL",
    "SALLOKE",
    "SANGO WALI",
    "SARDAR PUR SEHGAL",
    "SAROKI",
    "SARWALA",
    "SHER PUR",
    "SINGH",
    "SINGHPURA",
    "SIRAN WALI",
    "SOHDHRA",
    "TAHLI WALA",
    "TALWARA",
    "THAT",
    "THATHA FAQIR ULLAH",
    "THATTI BALOCH",
    "THOIAN",
    "UNCHA KALER",
    "VEROKE",
    "WADALA",
    "WANJO WALI",
    "WAYAN WALI",
    "WAZIR KE CHATHA",
    "WAZIRABAD",
  ],
};

Map<String, dynamic> two = {
  "NA": 80,
  "Candidates": [
    "Zabeeh Ullah Balaggan",
    "Amir yaqoob Waraich",
    "Imtiaz Safdar Warraich",
    "Muammad Nasir Cheema",
    "Muhammad Arshad",
    "Muhammad Aslam",
    "Qazi Wasif Nadeem",
    "Rana Naeem Ur Rehman Kh..",
    "Shazia Bano Mazhar Java..",
    "Sultan Ahmad Warraich",
    "Uzair Ahmed",
    "Zain Ali Bhatti",
    "Muhammad Ubaid Ullah",
    "Ch Mehmood Bashir Virk",
    "Rao Ikram Ali Khan",
    "Tariq Mehmood",
    "Muhammad Ahmed"
  ],
  "Party": [
    "AOAT",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "MMAP",
    "PMLN",
    "PPPP",
    "PTI",
    "TLP"
  ],
  "Areas": [
    // "A1, A4, Aria Cantonment",
    // "Akram Colony Darbar Allah Hoo Gill Road",
    // "Akram Colony, Sadat St. Cannal Colony",
    // "Allama Iqbal Road Shaheen Abad",
    // "Allama Iqbal Town Cantonmen",
    // "Allama Iqbal Town, Khushi Town Cantonment",
    // "Amin Pur Kalangujranwala Cantonment",
    // "Army Officer Quarter, Near 8th Avenue Cantonment",
    // "Ashfaq Abad (Qila Chait Singh)",
    // "Askari Homes Phase-I,Gujranw ala Cantonmen",
    // "B- Block Gulshan Park",
    // "B4, B5, B6, Aria Cantonment",
    // "Babu Chak jaial",
    // "Baddoki Ghosian Gujranwala Cantonment",
    // "Baghat Garh Gujranwala Cantonment",
    // "Balley Wala",
    // "Barkat Colony Shaheen Abad",
    // "Bawara Dhak Walo",
    // "Bazar Area Bank Morr Cantonment",
    // "B-Block Mohallah Insarian/Shahee nabad",
    // "Behlad Pur",
    // "Bhakhray Wali Khurd",
    // "Bijjo Mil",
    // "Bilal Street Sharif Form Cantonment",
    // "Bilal Town Gujranwala Cantonment",
    // "Botala Sardar Jhanda Singh",
    // "Bukhari Road Railway Qarater Gil Road",
    // "Bukhari/Gill Road",
    // "Butranwali",
    // "C- Block Shaheen Abad",
    // "Cavelary Area D1 Cantonment",
    // "C-Block Main Bazar Shaheenaba",
    // "C-Block Nobel Fan Shaheenabad",
    // "Chahal Kalan",
    // "Chahal Nau",
    // "Chak Baig",
    // "Chak Jaid",
    // "Chak Uggo",
    // "Chander Key",
    // "Ci Area Cantonment",
    // "D-Block Insarian",
    // "Defence Phase-Ii Cantonment",
    // "Dheer Virkan",
    // "Dhido Duggal",
    // "Dogranwala",
    // "E Block Avenue Road",
    // "E2, 3 G2,3, Cantonment",
    // "E4 Tanki No. 5 Cantonment",
    // "Es, Issb Chowk Cantonment",
    // "F1 Quarter Tanki No.7Gujranwala Cantonment",
    // "Fazal Pura",
    // "Gage Wali",
    // "Gajjo Chak",
    // "Gal Mehar Nawaz Counsilar Atta M. Road",
    // "Garhi Himmat Singh",
    // "Girls School, Jamia Masjid Bilal, Christian Abadi, Kashmir Clony",
    // "Gondlan Wala",
    // "Green Town, Peero Shaheedgujranwala Cantonment",
    // "GT Road Bhatian Nagar",
    // "Gulab Pura Mohallah Gujjran",
    // "Gulab Pura Mohallah Gujjran Cantonment",
    // "Haiger",
    // "Hardo Deori",
    // "IB Area Near Tanki No.7 Haidery Chowk Cantonment",
    // "Jatan Wala, Loharan Wala Cantonment",
    // "Javaid Town Mujahid Colony, Shaheenabad",
    // "Johid Pur",
    // "Kabaria Chowk Sheenabad",
    // "Kalou Wali",
    // "Kamo Malhi",
    // "Kashmir Collony",
    // "Kashmir Colony Gujranwala Cantonment",
    // "Khabbey Key",
    // "Khakheke",
    // "Khaliq Pur",
    // "Khewa Duggal",
    // "Kot Amar Singh",
    // "Kot Asaish",
    // "Kot Bary Khan",
    // "Kot Bhawani Das",
    // "Kot Bola",
    // "Kot Khaliq",
    // "Kot Miran G (Qila Balwant Singh)",
    // "Kot Piro Shah",
    // "Kot Qazi",
    // "Kot Saad Ullah",
    // "Kot Shah",
    // "Kot Shahan",
    // "Kotli Bakha",
    // "Kotli Balgo Bind (Rait Wali)",
    // "Kotli Lakha",
    // "Kotli Pir Ahmed Shah (Kotli Jodh Singh)",
    // "Kotli Sabbo",
    // "Ladhewala Waraich",
    // "Dhullay",
    // "Main Bazar Gulshin Iqbal Park Shaheen Abad",
    // "Main Bazar, Gali Raj Potangujranwala Cantonment",
    // "Main Bazar, Kashmirian Cantonment",
    // "Mandiala Warraich",
    // "Masaikey Wali",
    // "Mirza Colony, Noor Mustifa Colony",
    // "Model Town",
    // "Shumali",
    // "Mohallah B 4 Area Gujranwala Cantonment",
    // "Mohallah B 6 Area Gujranwala Cantonment",
    // "Mohallah Fazal Pura Shaheenabad",
    // "Mohallah Gaoo Shala Miller Road",
    // "Mohallah Ghari Shaho, Cantonment",
    // "Mohallah Ghari Shaho, Muslim Town, Sharif Pura, Cantonment",
    // "Mohallah Gulab Pura Cantonment",
    // "Mohallah Jattan. Mohallah Kashmiran Cantonment",
    // "Mohallah Mughalan Tanki Wala Kashmir Colony",
    // "Mohallah Salamat Pura Cantonment",
    // "Mughal Pura Amrat Puragujranwala Cantonment",
    // "Muhammad",
    "Musa Duggal",
    "Nai Purani Abady Dhullay",
    "Nlc Workshop, Cantonment",
    "Nobal Fan B-Block",
    "Papnakha",
    "Pipli Wala",
    "Qabristan Road Gali Maryyam Nawaz",
    "Qaim Pur",
    "Qila Dev",
    "Qila Didar Singh",
    "Qila Sujan Singh",
    "Qila Wazir Singh",
    "Radiala Warraich",
    "Rajkot",
    "Rasoorpura",
    "Sahankey",
    "Saman Abad",
    "Saman Abad / Shaheen Abad",
    "Samrai",
    "S-Block, Taranwala Gala Mohallah Insarian",
    "Shafi / Shama Colony",
    "Shahray Quaid-E-Azam Green Town Gujranwala Cantonment",
    "Shama Colony Sharif Pura",
    "Sharif Pura, Cantonment",
    "Small Industry",
    "Soian",
    "Shaheenabad",
    "Talwandi Khajoor Wali",
    "Talwandi Rahwali",
    "Tarigri",
    "Tathi Daswandi",
    "Thakarkey",
    "Thatta Basau",
    "Thatta Dad",
    "Zahid / Shafi / Shama Colony",
    "Zahid Colony"
  ],
};

Map<String, dynamic> three = {
  "NA": 81,
  "Candidates": [
    "Muhammad Naseem Sadiq",
    "Shahid Hameed",
    "Atif Farid Sabir Khan",
    "Kashif Sabir Khan",
    "Muhammad Rafiq",
    "Nasir Afzal",
    "Naveed Anwar Bhinder",
    "Usman Saeed",
    "Hameed Ud Din Awan",
    "Khurram Dastgir Khan",
    "Muhammad Anas Amjad",
    "Chaudhry Muhammad Siddi..",
    "Muhammad Ishaq"
  ],
  "Party": [
    "ALPP",
    "AOAT",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "MMAP",
    "PMLN",
    "PPPP",
    "PTI",
    "TLP"
  ],
  "Areas": [
    "Block Gulzar Colony",
    "Abadi Muhammad Bux",
    "Abdal",
    "Abid Colony",
    "Ahmed Pura",
    "Ahsan Town",
    "Akbri Road Chah Noorang",
    "Akbri Road Gondalanwala Road",
    "Ali Park",
    "Allah Bux Collony",
    "Amir Park",
    "Androon Basti Dogran",
    "Arfat Colony Gali No. 17",
    "Aroop",
    "Arshad Town",
    "Asghar Ali Road",
    "Asghar Colony",
    "Aziz Collony Gulzar Colony",
    "Block Gulzar Colony",
    "Model Town",
    "Setllite Town",
    "Balla Chowk Settlite Town",
    "Barri Civil Line",
    "Bazar Almarian",
    "Bazar No.2 Arfat Colony",
    "Behaari Colony",
    "Bheko pura Kachi Fatomand",
    "Block No.2 Mujahid Pura",
    "Block Gulzar Colony",
    "Caperi Colony",
    "Chak Khizar",
    "Chaman Shah Road",
    "China Walai Abadi Islamia Park, Jinnah Rd",
    "Church Pasroor Road, Fareed Town",
    "Civil Line",
    "College Road",
    "Crown Ciman Chowk Islamia College Road",
    "D- Block Gulzar Colony",
    "D- Settlite Town",
    "Davi wala Talab",
    "DC Road",
    "Dera Ch. Jamshad Kashmir road",
    "Dispsal Road",
    "Dr. Fazal u Rehman Colloge Road",
    "Durra Phatic, Bhatia nagar",
    "Faisal Colony Muslim Bazar",
    "Faiz Alam Town",
    "Faqeer Pura",
    "Fareed Road",
    "Fareed Town Usman park",
    "Fazal Town Saeed Chowk",
    "Gala Church Wala Fareed Town",
    "Gala Papu Meharwala",
    "Gali Dr. Ali Jan",
    "Gali Karachi Bakeri Delta Road",
    "Gali Masjid Nimara Usman Park",
    "Gali No 8 D- Block Gulzar Colony",
    "Gali No. 11 Ali Park",
    "Gali No.1 Moh Habib Ullah Jalani",
    "Gali No.12 Arfat Colony",
    "Gali No.12,13 21,24,25",
    "Gali No.22 Arfat Colony",
    "Gali No.29 Irfat Colony",
    "Gali No.4 Kanwar Garh",
    "Gali No.6 Farooq Gunj",
    "Gali No.8 Rasheed Colony",
    "Gali No.9 Faqeer Pura",
    "Gali Qabarstan Fareed Town",
    "Gali Tahali Wali/ Gala Mano Butt",
    "Galli No. 6 Faqeer Pura",
    "Garjakhi Chowk Lakar Wala Bazar",
    "Garjakhi Darwaza",
    "Ghazi Pura, Mandir Bavi wala",
    "Ghor Dorr Road",
    "Ghulam Mustifa Suleharia Chowk",
    "Ghusia Abad/ Muafi wala Chowk",
    "Ghusia Abad/Faisal Town/Ashraf Colony/Usman Chowk",
    "Girls Hostel Settlite Town",
    "Gobind Garah Chah Noorang",
    "Gobind Garh / Kunwar Garh",
    "Gobind Garh Nauman Pura",
    "Goray wala Khoh/ Islamia Park",
    "Gulzar Colony",
    "Haidery Road Mujahid pura Muslim Bazar",
    "Herdo Chichar Wali",
    "Herdo Chichar Wali, Moh. Rasool Nagar",
    "Hussan Town Latif Socity",
    "Ibraheem Park",
    "Ibraheem Park Gulzar Colony",
    "Imran Colony Fatomand",
    "Iqbal Gunj Colloge road",
    "Irfat Colony Haidery Road",
    "Islamia Park Allah Wala Bazar",
    "Jagna Main Bazar to Mh. Iftikhar Pehalwan",
    "Jagna Sialkot Road",
    "Jahangeer Colony",
    "Jinnah Road",
    "Jinnah Road Duban Pura",
    "Jinnah Road Fato Mand",
    "Jinnah Town, Kashmir Colony",
    "Kachi Abadi Settlite Town",
    "Kachi Fatomand",
    "Kamboh Colony",
    "Kangani Wala",
    "Kangani Wala, Kot Abdullah",
    "Kanwar Garh Colloge Road",
    "Kasera Bazar, Gali Bhabarrian",
    "Kasera Bazar, Gali Thathiarrian/Man charian, Said Naga",
    "Kasera Bazar, Gali Thathiarrian/Man charian, Said Nagar",
    "Kashmeer Road",
    "Kashmeer Road Usman Park Ali Park",
    "Kashmir Colony",
    "Kashmir Road Haidery Chowk",
    "Khand Bazar Haji Pura",
    "Khoh Falorian",
    "Khokhar Ki",
    "Khothi Barkat Ram Dastgeer Road",
    "Khothi Barkat Ram Delta Road",
    "Kot Habib Ullah",
    "Kotli Audho",
    "Lakar Wala Pol Mustifa Chowk",
    "Lohianwala",
    "Lohianwala (Moh. Ali Asghar Colony)",
    "Lohianwala (Moh. Gorey wala)",
    "Lohianwala (Moh. Jamia Masjid Ahle Hadidh)",
    "Madinna Colony",
    "Main Dina Nagar Rd Pondanwal",
    "Main Road Abid Colony",
    "Marrian Road",
    "Marrian Road Moh. Bilal Pura",
    "Meran G Town / Madina Town",
    "Minhas Pura",
    "Minhas Pura / Naz Ciman",
    "Model Town",
    "Moh Islam Abad",
    "Moh. Faisal Abad",
    "Moh. Faisal Abad,Gondalanw ala Road",
    "Moh. Islam Abad",
    "Moh. Noor Bawa 728 728",
    "Moh. Noor Pura Fatomand/Sialkot Road",
    "Moh. Salamat Pura",
    "Muhallah Islampura",
    "Muhallah Islampura Haidery Road",
    "Muhammad Pura",
    "Mujahid Pura Haidary Road",
    "Mujahid Pura Kachi Dam Geer Wali",
    "Mukhtar Colony, Jinnah Road Haji Park",
    "Mustifa Abad",
    "Muzal Colony/ Qasim Town",
    "Nai Abadi Alama Iqbal Town",
    "Nai Abadi Jagna Sialkot Road",
    "Nasir Colony",
    "National Town Mughal Chowk",
    "Nauman Pura",
    "Naumania Road Ahmed Pura",
    "Nawaz Colony",
    "New Civil Line",
    "New Civil Line Behind Old Bijili Ghar",
    "Nika Chowk Dagan wala Bazar",
    "Noor Pur/ Fatomand Road Agency Tailwali",
    "Noor Pura /Jinnah Road Fatomand Roa",
    "Noor Pura, Agency Tail wali Jinnah Road",
    "Parraoo Camp No.4",
    "Parraoo Camp No.4 Wapda Colony",
    "Pasroor Road",
    "Pasroor Road Fareed Town",
    "Peoples Colony",
    "Police Line Kamboh Colony",
    "Popular Nursari",
    "Popular Nursary",
    "Puran Jagna",
    "Puran Jagna , Abbass Colony",
    "Puran Jagna , Mukhtar Colony",
    "Purani Abadi Jagna",
    "Qasam Town Ratta Road",
    "Raice Course Road Nasir Colony",
    "Rail Bazar",
    "Raja / Gulzar Colony",
    "Rana Colony",
    "Rasheed Colony",
    "Rasheed Colony Bazar No.2",
    "Rataa Road",
    "Rattanwala",
    "Rattanwala, Model Town",
    "Sabri Chowk",
    "Saddique Colony",
    "Said Nagari, Bazar GT Road,Rail Bazar",
    "Saithy Palaza",
    "Saleem Colony",
    "Sango Wali",
    "Sangum DC Road Afzal Colony Railway Rd",
    "Setllite Town",
    "Shadaman Town",
    "Shah Din Wala bazar Fareed Town",
    "Shamas Abad Feroz wala Road",
    "Shan Marriage Hall",
    "Shaukat Abat Malik Park",
    "Shehzada Shaheed Colony",
    "Sialkoti Gate",
    "Siddiqu Akbar Park",
    "Sui Gass",
    "Sui Gass Link",
    "Sui Gass Road",
    "Sultan Pura",
    "Tail wali Agency",
    "Tail wali Agency Jinnah Road",
    "Therri Sansi",
    "Urfat Colony",
    "Urfat Colony, Chamarra Mandi",
    "Usman Colony/ Mughal Chown",
    "Wahdat Colony",
    "Wania Wala",
    "Wazir / Hamid Colony",
    "W-Block Peoples Colony",
    "Y-Block Peoples Colony",
    "Z-Block Gali No.13-20 Peoples Colony",
    "Z-Block Gali No.2 to Takbir Road",
    "Z-Block Gali No.2-9 Peoples Colony",
    "Z-Block Gali No.9-13 Peoples Colony",
    "Z-Block Gali Z to Cannal Road"
  ],
};

Map<String, dynamic> four = {
  "NA": 82,
  "Candidates": [
    "Abdul Karim",
    "Nafisa Tahira",
    "Aman Ullah Butt",
    "Ahsan Yousaf",
    "Ch. Muhammad Younas Ali",
    "Faisal Adnan Sandhu",
    "Muhammad Farooq",
    "Muhammad Imran",
    "Shahid Usman",
    "Shoukat Ali",
    "Usman Ashraf",
    "Usman Ibrahim ",
    "Muhammad Furqan ",
    "Usman Ibrahim",
    "Lshaq Akbar",
    "Ali Ashraf Mughal",
    "Muhammad Ashraf Asif",
    "Shahbaz Khan",
    "Usman Saif"
  ],
  "Party": [
    "AAP",
    "ALPP",
    "AOAT",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "MMAP",
    "PMLN",
    "PPPP",
    "PTI",
    "TLI",
    "TLP",
    "TTNP"
  ],
  "Areas": [
    "Abadi Kelay Wali",
    "Abadi Lal Hussain",
    "Abadi Mehar Mehar Wazir",
    "Abadi Mehar Wazir",
    "Abadi Mehar Wazir Moman Abad",
    "Abadi Murabay KarKhanay Wali",
    "Abbass Pura, Garjakh",
    "Abu Bakar Park",
    "Ajmal Town",
    "Ajmal Town/ Gulbarg",
    "Alam Chowk",
    "Alam Chowk-Roz Gaurden Marriage hall",
    "Ali G Town, Sadiq Abad",
    "Ali Pur Chowk Janat Town",
    "Amen Abadi Darwaza",
    "Andoorn Khiali Gate",
    "Androon Amen Abadi Gate",
    "Androon Basti Dogran",
    "Asad Colony",
    "Asad Colony , Cheema Abadi",
    "Asif Colony Madina Colony",
    "Asmat Ullah Town",
    "Awais Park Javaid Town Mian Sansi",
    "Babar General Store/ Gali Haroon wala",
    "Baghbanpura Hafizabad Road",
    "Bakhtay Wala",
    "Bari wala Road",
    "Barra Gali Noshehra Road",
    "Bashir Sar Gar (Late) Dhullay",
    "Bath Colony/ Alam Chowk",
    "Bazar Babhraian road",
    "Bazar Gorray Shah Hafizabad Road",
    "Bhata Abadi",
    "Bilal Road",
    "Bukhari Colony",
    "Chah Sarafan",
    "Chah Talianwala Noshehra Road",
    "Chand Karyana Store",
    "Chiragh Nagar",
    "Chowk Baghbanpura Mehr Muzafar Road",
    "Chowk Ghanta Ghar Circular Road",
    "Chowk Melad Mustifa",
    "Chowk Melade Mustifa, Kachay Bartan wala Bazar",
    "Chowk Nathay Wala",
    "Colony Haji Ghulam Hussain Kalar Abadi",
    "Crown Ciman Garjakh",
    "Darbar Hussain Shah",
    "Darogha / Gulzar Colony",
    "Faisal Colonly",
    "Farooq Gunj",
    "Farooq Gunj",
    "Farooq Gunj / Kashmeer Town No.2",
    "Farooq Gunj Liaqt Road",
    "Firdous Colony",
    "Gali Abdul Rehman Dhool Wala",
    "Gali Aray wali",
    "Gali Ayub Sindhu",
    "Gali Baghwali Garjakh Road",
    "Gali Barazan Baghechi Chowk",
    "Gali Bhai Sattar Garjakh",
    "Gali Chah Bawian, Mubarik Shah Road",
    "Gali Chawalianwali Chowk Bari wala",
    "Gali Darbar Wala Mian sansi",
    "Gali Dipo Wala",
    "Gali Dipowala Garjakh",
    "Gali Disposal Dhullay",
    "Gali Dr. Khadim Dhullay",
    "Gali Garh Talian Hafiz Abad Road",
    "Gali Ghulam Hussain",
    "Gali Ghulam Muhammad Thakedar",
    "Gali Ghulam Muhammad Thakedar Gal Mehar Bagoo wala",
    "Gali Goga Pehlwan",
    "Gali Haji Abdul Kareem",
    "Gali Haji Amir Din",
    "Gali Hameed Wala Jinnah Road Dhulay",
    "Gali Kohlowali Dhullay",
    "Gali Masjid Bahar Madina Dhullay",
    "Gali Meeran Shah",
    "Gali Mehar Bagoo Wala Muslim Road",
    "Gali Mehar Noor Wala",
    "Gali Mehar Noor Wala/Ghulam Muhammad Thekedar wala",
    "Gali Monshi Aslam",
    "Gali Muhammad Rafiq Main Sheikhupura Road",
    "Gali Natho Jutt , Khair Din",
    "Gali No. 1 to 6 Mohallah Hamed Pura",
    "Gali No.1 Afzal Pura",
    "Gali No.1 to 6 Abbas Pura Garjakh",
    "Gali No.1, 2 Mohallah Rehman Pura",
    "Gali No.12 Momin Abad- A",
    "Gali No.2 Babo Nasir Uldin",
    "Gali No.2 Baghbanpura",
    "Gali No.2,3 Kareem Pura",
    "Gali No.2,3 Mohallah Rehman Pura",
    "Gali No.25 Gulshen Abad Sher Sing",
    "Gali No.2-8 Gali Goga Pehlwan",
    "Gali No.3 School Wali",
    "Gali No.4 Muslim Town",
    "Gali No.5 Hanif Khokhar",
    "Gali No.5-8 Haji Abdul Kareem",
    "Gali No.6 Gali Beruf Wala",
    "Gali Paratan Wali",
    "Gali Qadiria Darbar Hafizabad",
    "Gali Qadria Darbal , Bushara Road",
    "Gali Sain Nawab",
    "Gali School Wali Mukhtar Colony",
    "Gali Shaukat Rehmani Noshehra Road",
    "Gali Tarana Wala- ChampionJim",
    "Gali Umar Farooq",
    "Ganda Nala Jinnah Road",
    "Garjakh Road",
    "Gharbi Tower Road Khiali",
    "Ghazi Abad",
    "Ghulam Fareed Road",
    "Ghulam Pura",
    "Girdo Niwa Tanki",
    "Gorray Shah / Gali Haroon",
    "Gulbarg Colony",
    "Gulistant Colony Mubarik Shah Road",
    "Gulshan Adeel Colony",
    "Gulshan Rehman",
    "Gulshen Abad",
    "Gulshin Colony",
    "Gulshin Karim",
    "Gulshin, Mumtaz,",
    "Gulshin, Mumtaz, Sarfaraz Colony",
    "Gulzar Colony",
    "Gulzar Colony/Asad Colony",
    "Hafizabad Road",
    "Haji Karim Peramedical Road",
    "Hameed Pura",
    "Hasan Pura",
    "Hashmi Colony",
    "Hassan Pura, Nawab Chowk",
    "Ibrahim Town",
    "Ibrahim Town",
    "Imran Colony /Salam Pura",
    "Islam Pura",
    "Islam Pura Dhullay",
    "Jamia Masjid Muhammadia",
    "Jamia Masjid Usmania Garjakh",
    "Jamia Muhammadia",
    "Jinnah Colony",
    "Jinnah Road Muhammad Nagar",
    "Jinnah Road, Azam Abad",
    "Judicial Colony",
    "Kalar Abadi Gorray Shah Road",
    "Kangni Wala",
    "Karim Pura",
    "Karwan Chowk Mian Sansi",
    "Kashmeer Colony Haji Murad Hospital",
    "Kashmir Colony",
    "Khalid colony Hafiz abad road",
    "Khalid Colony/ Sharif Pura",
    "Khand Bazar Haji Pura",
    "Khial Near Bye Pass Road",
    "Khiali Shahpur",
    "Khiali Sheikhupura Road",
    "Kohlo Wala",
    "Kotli Rustam",
    "Kotli Rustam. Alim Chowk",
    "Liaqat Colony",
    "Liaqat Road Gooro Nanik Pura",
    "Madina Bazar Chah Talian Wala",
    "Madina Chowk Silver Steel Works",
    "Madina Colony /Gulshin Colony",
    "Madina Markeet Dhullay",
    "Main Bazar",
    "Main Gali Muhammad Nagar",
    "Main Garjakh Road",
    "Main Sheikhupura Road",
    "Masjid Billal Gunj",
    "Masjid Khudad Mian Sansi",
    "Mehboob ul Haq",
    "Mian Sansi Bazar No.1 Ali Sher",
    "Moh Afzal Pura",
    "Moh Islam Abad",
    "Moh Qabaristan Garjakh",
    "Moh Tajpura Garjakh",
    "Moh. Bakhtay Wala",
    "Moh. Bakhtay Wala Allama Iqbal Road",
    "Moh. Chah Bagh Wala Garjakh",
    "Moh. Chah Baghwala",
    "Moh. Chah Baghwala Garjakh",
    "Moh. Chah Chuhanan wala",
    "Moh. Christian Abadi",
    "Moh. Ghusia Nai Abadi Daud Colony",
    "Moh. Noor Bawa",
    "Moh. Tariq Abad G.T Road",
    "Moh. Totianwala Garjak",
    "Moh. Totianwala Garjakh",
    "Moh.Pak waris Noshehra Road",
    "Mohallah Eid Gah Indonasia Garjakh",
    "Moman Abad-A",
    "Momin Abad Chah Talian Wala",
    "Momin Abad Noshehra Road",
    "Momin Abad-B",
    "Mubarik Colony Hafiz Abad Road",
    "Mughalpura Dhullay",
    "Muhammad Abad, Garjakh",
    "Muhammad Nagar Data Ganj Bux",
    "Muhammadi Town",
    "Mukhtar Colony",
    "Mukhtar Colony Main Bazar",
    "Muslim Town",
    "Muslim Town Gali No.10",
    "Mustifa Abad Tower Road",
    "Nadeem Abad",
    "Nai Abadi Noshehra Sansi",
    "Nalay Wali Gali Gulshin Abad",
    "Nasar Roar, Muslim Road",
    "Nasr ullah Abadi",
    "Naveed Colonly/ Sui gass Road",
    "Naveed Colony",
    "Nazad Qabaristan Garjakh",
    "Nazir Park Katcha Khiali Road",
    "Norani Road Jadeed Baghbanpura",
    "Noshehra Road Baghban pura jinnah road",
    "Noshehra Road Baghbanpura jinnah road",
    "Noshehra Sansi",
    "Noshehra Sansi (Qila Sundar Singh)",
    "Noshehra Sansi Road",
    "Noshera Sansi",
    "Porani Abadi Khiali Sharki",
    "Prince Road Masjid Toheed Garjakh",
    "Qaim Ali Shah Mian Sansi",
    "Qila Chand",
    "Qila Chand (Jalil Town)",
    "Qila Sundar Sing Awan Chowk",
    "Ramzan pura Ghorray Shah Road",
    "Rasheed Colony",
    "Raza Abad",
    "Rehman Pura",
    "Rehmat Pura",
    "Rehmat Pura / Sui Gass Road",
    "Rehmat Pura,",
    "Rehmat Pura, Rehman Abad",
    "Rehmat Town",
    "Sadiq Akbar Town",
    "Safdar Colony",
    "Said park",
    "Said Park Dhulay",
    "Salam Pura",
    "Saradar Colony",
    "Sardar Colony",
    "Sardar Colony/Madni Road",
    "Sarfaraz Colony",
    "Sarfaraz Colony, Mumtaz Colony",
    "Shadman / Umar Farooq Colony",
    "Shadman Colony",
    "Shafique General Store Noshera Road",
    "Shah Rukh Colony",
    "Shah Rukh Colony Hafizabad",
    "Shah Rukh Colony Hafizabad Road",
    "Shaheen Pura",
    "Shahpur",
    "Sharif Pura Mubarik colony",
    "Sharif Pura Shah Rukh Colony",
    "Sharif Shaheed Colony",
    "Shehbaz Colony",
    "Sheranwala Bagh, Thana wala Bazar",
    "Sialvi Town",
    "Siraj Pura",
    "Sui Gass Road",
    "Sultan Pura",
    "Tabaarik Colony Khiali Shahpur",
    "Taj pura",
    "Taj Town Mian Sansi",
    "Tariq Abad",
    "Tariq Abad Khalid Colony, Mominpura",
    "Tariq Abad Ramzan Pura",
    "Thana Khiali Shahpur",
    "Thana Wala Bazar Gali Fazal Din",
    "Tharri Sansi",
    "Tower Road",
    "Tower Road Khiali",
    "Usman Ghani Colony Noshehra Road",
    "Wasan Pura Umar colony",
    "Zubair Timber Hafizabad Road"
  ],
};

Map<String, dynamic> five = {
  "NA": 83,
  "Candidates": [
    "Chaudhary Zulfiqar Ali Bhinder",
    "Rana Nazir Ahmed Khan",
    "Ch.Zaka Ullah Baryar",
    "Ch.Ali Wakeel Khan",
    "Rana Umar Nazir Khan",
    "Saeed Yousaf Bhindar",
    "Shabaz Ahmad",
    "Qamar Hussain",
    "Muhammad Nasir Mehmood",
    "Mian Asif Ali"
  ],
  "Party": [
    "PMLN",
    "PTI",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "PTIG",
    "TLP",
    "PPPP"
  ],
  "Areas": [
    "Ahmed Pur Virkan (Jhior)",
    "Akbar Abad",
    "Akbar Ghanoke",
    "AKBARIAN",
    "Ali Pur (Chak Ram Das Purana)",
    "Allah Abad (Nangal Doona Singh)",
    "Ameen Pur",
    "Ashraf Abad (Sunnat Pura)",
    "ATTAWA",
    "BABBAN",
    "BAGHWALA",
    "Baqa Pur",
    "BASI WALA",
    "BAWARE",
    "BHAMMUNWALI",
    "Bharar",
    "Bharoki Virkan",
    "BHATTI BHANGO",
    "Bheelo Wali",
    "Bhoopar",
    "Bhorari",
    "Boley",
    "Booty Wali",
    "BOTALA SHARAM SINGH",
    "Boulo Wali",
    "Budhu Pur (Bilal Pur)",
    "Chak Alao Din",
    "Chak Gillan",
    "CHAK HINDU",
    "Chak Joia",
    "CHAK MUSLIM",
    "CHAK NIZAM",
    "Chak Ramdas Nau",
    "Chak Rehan",
    "Chak Warraich",
    "Chakian Kalan",
    "Chakian Khurd",
    "Chanawan",
    "CHANDALA",
    "CHANDALI",
    "CHHAJOKI",
    "DALIAN WALI",
    "DANDIAN",
    "DARAJKE",
    "DARGA PUR",
    "DATEY WALI",
    "DENSAR BALA",
    "Dhang",
    "Dhang Wali",
    "Dhapai",
    "Dharang",
    "DHATTAL",
    "Dheer Wali",
    "DHENSAR PAIN",
    "DHERAM KOT",
    "Dhodke",
    "DHOLAN",
    "DHUP SARI",
    "Douburji",
    "Dougal",
    "Doulowali Abad",
    "Doulowali Viran",
    "Fazal Pur",
    "FEROZ WALA",
    "Gagarke",
    "Gandum",
    "Gauna Aur",
    "Ghazi Chowk",
    "GHHANIAN",
    "GHOGA",
    "GHOMAL",
    "Gilgitti",
    "Gorala",
    "Gorali",
    "GULLO KE",
    "Habib Pura (Qila Sukha Singh)",
    "Haider Abad (Thatha Ghulab Singh)",
    "Hameed Pur Kalan",
    "Hameed Pur Khurd",
    "HARDO KHOT",
    "Hayat Pur",
    "Hayati",
    "HERPOKI",
    "Hoye Wali",
    "Inayat Pur",
    "Jabboke",
    "Jandiala Baghwala",
    "Jandiala Baghwala M0h Qabiristan wala",
    "Jandiala Baghwala Moh Bhopal wala",
    "Jandiala Baghwala Moh waris kot",
    "Kala",
    "KALAR",
    "Kali Suba",
    "KALLU KALLAN",
    "KAMOKE M.C. (Moh. Baldia Office)",
    "KAMOKE M.C. (Moh. Ghalla Mandi, Rail Bazar)",
    "KAMOKE M.C. (Moh. Kot Rafique)",
    "KAMOKE M.C. (Moh. Model Town, Mandi Arhtian)",
    "KAMOKE M.C. (Moh. Muslim Ganj Sadar Abad)",
    "KAMOKE M.C. (Moh. Muslim Ganj)",
    "KAMOKE M.C. (Moh. Muslim Ganj)",
    "KAMOKE M.C. (Moh. Muslim Ganj, Moh.Ghosia)",
    "KAMOKE M.C. (Moh. Pak Town)",
    "KAMOKE M.C. (Moh.Bilal Park)",
    "KAMOKE M.C. (Sheesh Mahal Road)",
    "Kamoke MC ( Moh. Haidry)",
    "Kamoke MC ( Moh. Haidry, Gali Jahaz Wali)",
    "Kamoke MC ( Moh. Haidry, Sheesh Mahal Road)",
    "Kamoke MC ( Moh. Mandiala Road)",
    "Kamoke MC ( Moh. Mandiala Road, Sheesh Mahal Road)",
    "Kamoke MC ( Moh. Alamgir Road, Moh. Haidry)",
    "Kamoke MC ( Moh. Gol Bazar)",
    "Kamoke MC ( Moh. Haidry)",
    "Kamoke MC ( Rasool Nagar)",
    "Kamoke MC ( Tatley Road)",
    "Kamoke MC (Bilal Park)",
    "Kamoke MC (Dera Baba Jani)",
    "Kamoke MC (Dhoop Sari)",
    "Kamoke MC (Haidry, Sheesh Mahal Road",
    "Kamoke MC (Karmanwala, Tibba Muhammad Nagar",
    "Kamoke MC (Karmanwala, Tibba Muhammad Nagar)",
    "Kamoke MC (Kassoke Road)",
    "Kamoke MC (Kassoke Road, Nai Mandi)",
    "Kamoke MC (Kassoki Road, Rasool Nagar)",
    "Kamoke MC (Mah. Hajvery)",
    "Kamoke MC (Moh. Bahar Shah)",
    "Kamoke MC (Moh. Chandni Chowk)",
    "Kamoke MC (Moh. Darvaish Pura)",
    "Kamoke MC (Moh. Dhoop Sari)",
    "Kamoke MC (Moh. Dolat Pura)",
    "Kamoke MC (Moh. Faisal Town)",
    "Kamoke MC (Moh. Faiz e Madina)",
    "Kamoke MC (Moh. Ghulam Abad)",
    "Kamoke MC (Moh. Habib Pura)",
    "Kamoke MC (Moh. Karim Pura)",
    "Kamoke MC (Moh. Khokhar Pura)",
    "Kamoke MC (Moh. Latif Abad)",
    "Kamoke MC (Moh. Malik Pura)",
    "Kamoke MC (Moh. Mir Khurram)",
    "Kamoke MC (Moh. Mushtaq Pura)",
    "Kamoke MC (Moh. Nai Abadi)",
    "Kamoke MC (Moh. Riaz Pura)",
    "Kamoke MC (Moh. Sardar Pura)",
    "Kamoke MC (Moh. Shahi Road)",
    "Kamoke MC (Moh. Tahli Mohri)",
    "Kamoke MC (Moh. Tahli Mohri)",
    "Kamoke MC (Moh. Tibba Muhammad Nagar)",
    "Kamoke MC (Moh. Usman Pura)",
    "Kamoke MC (Moh. Wapda Town)",
    "Kamoke MC (Mohalla Sarai wala)",
    "Kamoke MC (Rasool Nagar)",
    "Kamoke MC (Sheesh Mahal Road)",
    "Kamoke MC (Sultan Pura)",
    "Kamoke MC (Tatli Sarai)",
    "Kamoke MC (Usman Pura)",
    "Kamoke MC (Zafar Iqbal Colony)",
    "Kamoke MC (Zakriya Pura)",
    "Kamoke MC (Zakriya Pura, Kot Ishaq)",
    "Kamoke MC (Zakriya Pura, Tibba Muhammad Nagar)",
    "Kamoke MC (Zakriya Pura)",
    "Kamoke MC (Zakriya Pura, Tibba Muhammad Nagar)",
    "KAMOKE UC NO. 02 (Moh. Ghalla Mandi)",
    "KAMOKE UC NO. 03 (Moh. Nai Abadi)",
    "KAMOKE UC NO. 04 (Moh. Zakriya Pura)",
    "KAMOKE UC NO. 05 (Moh. Nai Abadi)",
    "KAMOKE UC NO. 06 (Moh. Kamboh Pura)",
    "KAMOKE UC NO. 07 (Moh. Tahli Mohri)",
    "KAMOKE UC NO. 08 (Moh. Qaim Pura)",
    "KAMOKE UC NO. 09 (Moh. Chak Faiz Muhammad)",
    "KAMOKE UC NO. 10 (Moh. Kot Kamber)",
    "KAMOKE UC NO. 11 (Moh. Kamoke Cantt)",
    "KAMOKE UC NO. 12 (Moh. Shah Din)",
    "KAMOKE UC NO. 13 (Moh. Dolat Pura)",
    "KAMOKE UC NO. 14 (Moh. Lalewal Mohalla)",
    "KAMOKE UC NO. 15 (Moh. Kotli Bheeka)",
    "KAMOKE UC NO. 16 (Moh. Nai Abadi)",
    "KAMOKE UC NO. 17 (Moh. Bakarwal)",
    "KAMOKE UC NO. 18 (Moh. Kamoke Cantt)",
    "KAMOKE UC NO. 19 (Moh. Kot Ishaq)",
    "KAMOKE UC NO. 20 (Moh. Sharifpura)",
    "KAMOKE UC NO. 21 (Moh. Ghalla Mandi)",
    "KAMOKE UC NO. 22 (Moh. Ghalla Mandi)",
    "KAMOKE UC NO. 23 (Moh. Zahoor Pura)",
    "KAMOKE UC NO. 24 (Moh. Fateh Garh)",
    "KAMOKE UC NO. 25 (Moh. Taj Colony)",
    "KAMOKE UC NO. 26 (Moh. Madina Colony)",
    "KAMOKE UC NO. 27 (Moh. Dolat Pura)",
    "KAMOKE UC NO. 28 (Moh. Model Town)",
    "KAMOKE UC NO. 29 (Moh. Lakhan Kharri)",
    "KAMOKE UC NO. 30 (Moh. Ahmad Pura)",
    "KAMOKE UC NO. 31 (Moh. Dhoop Sari)",
    "KAMOKE UC NO. 32 (Moh. Sher Zaman Pura)",
    "KAMOKE UC NO. 33 (Moh. Bilal Park)",
    "KAMOKE UC NO. 34 (Moh. Lalazari)",
    "KAMOKE UC NO. 35 (Moh. Dhoop Sari)",
    "KAMOKE UC NO. 36 (Moh. Bhatti Pura)",
    "KAMOKE UC NO. 37 (Moh. Khokhar Pura)",
    "KAMOKE UC NO. 38 (Moh. Shama Colony)",
    "KAMOKE UC NO. 39 (Moh. Hayat Pura)",
    "KAMOKE UC NO. 40 (Moh. Habib Pura)",
    "KAMOKE UC NO. 41 (Moh. Fateh Garh)",
    "KAMOKE UC NO. 42 (Moh. Gulshan Iqbal)",
    "KAMOKE UC NO. 43 (Moh. Tahli Mohri)",
    "KAMOKE UC NO. 44 (Moh. Bhatti Pura)",
    "KAMOKE UC NO. 45 (Moh. Hayat Pura)",
    "KAMOKE UC NO. 46 (Moh. Model Town)",
    "KAMOKE UC NO. 47 (Moh. Islam Pura)",
    "KAMOKE UC NO. 48 (Moh. Majeed Pura)",
    "KAMOKE UC NO. 49 (Moh. Fateh Garh)",
    "KAMOKE UC NO. 50 (Moh. Habib Pura)",
    "KAMOKE UC NO. 51 (Moh. Shehzad Pura)",
    "KAMOKE UC NO. 52 (Moh. Ghosia Colony)",
    "KAMOKE UC NO. 53 (Moh. Dhoop Sari)",
    "KAMOKE UC NO. 54 (Moh. Chah Dholi)",
    "KAMOKE UC NO. 55 (Moh. Faisal Town)",
    "KAMOKE UC NO. 56 (Moh. Tariq Colony)",
    "KAMOKE UC NO. 57 (Moh. Malik Pura)",
    "KAMOKE UC NO. 58 (Moh. Lakhan Kharri)",
    "KAMOKE UC NO. 59 (Moh. Fatima Colony)",
    "KAMOKE UC NO. 60 (Moh. Usman Pura)",
    "KAMOKE UC NO. 61 (Moh. Lalewal Mohalla)",
    "KAMOKE UC NO. 62 (Moh. Lalewal Mohalla)",
    "KAMOKE UC NO. 63 (Moh. Zafar Iqbal Colony)",
    "KAMOKE UC NO. 64 (Moh. Model Town)",
    "KAMOKE UC NO. 65 (Moh. Ghalla Mandi)",
    "KAMOKE UC NO. 66 (Moh. Bhatti Pura)",
    "KAMOKE UC NO. 67 (Moh. Shehzad Pura)",
    "KAMOKE UC NO. 68 (Moh. Fateh Garh)",
    "KAMOKE UC NO. 69 (Moh. Fateh Garh)",
    "KAMOKE UC NO. 70 (Moh. Muhammad Nagar)",
    "KAMOKE UC NO. 71 (Moh. Jinnah Colony)",
    "KAMOKE UC NO. 72 (Moh. Muslim Town)",
    "KAMOKE UC NO. 73 (Moh. Asad Pura)",
    "KAMOKE UC NO. 74 (Moh. Ghalla Mandi)",
    "KAMOKE UC NO. 75 (Moh. Ghalla Mandi)",
    "KAMOKE UC NO. 76 (Moh. Fateh Garh)",
    "KAMOKE UC NO. 77 (Moh. Muslim Town)",
    "KAMOKE UC NO. 78 (Moh. Latif Abad)",
    "KAMOKE UC NO. 79 (Moh. Noor Pura)",
    "KAMOKE UC NO. 80 (Moh. Noor Pura)",
    "KAMOKE UC NO. 81 (Moh. Muslim Town)",
    "KAMOKE UC NO. 82 (Moh. Kamboh Pura)",
    "KAMOKE UC NO. 83 (Moh. Dolat Pura)",
    "KAMOKE UC NO. 84 (Moh. Rasool Nagar)",
    "KAMOKE UC NO. 85 (Moh. Sultan Pura)",
    "KAMOKE UC NO. 86 (Moh. Zahoor Pura)",
    "KAMOKE UC NO. 87 (Moh. Ghalla Mandi)",
    "KAMOKE UC NO. 88 (Moh. Hayat Pura)",
    "KAMOKE UC NO. 89 (Moh. Majeed Pura)",
    "KAMOKE UC NO. 90 (Moh. Kot Ishaq)",
    "KAMOKE UC NO. 91 (Moh. Jinnah Colony)",
    "KAMOKE UC NO. 92 (Moh. Islam Pura)",
    "KAMOKE UC NO. 93 (Moh. Model Town)",
    "KAMOKE UC NO. 94 (Moh. Fateh Garh)",
    "KAMOKE UC NO. 95 (Moh. Faisal Town)",
    "KAMOKE UC NO. 96 (Moh. Lalewal Mohalla)",
    "KAMOKE UC NO. 97 (Moh. Muslim Town)",
    "KAMOKE UC NO. 98 (Moh. Ghalla Mandi)",
    "KAMOKE UC NO. 99 (Moh. Muslim Town)",
    "KAMOKE UC NO. 100 (Moh. Qaim Pura)",
    "KAMOKE UC NO. 101 (Moh. Chah Dholi)",
    "KAMOKE UC NO. 102 (Moh. Zakriya Pura)",
    "KAMOKE UC NO. 103 (Moh. Rasool Nagar)",
    "KAMOKE UC NO. 104 (Moh. Shehzad Pura)",
    "KAMOKE UC NO. 105 (Moh. Taj Colony)",
    "KAMOKE UC NO. 106 (Moh. Muslim Town)",
    "KAMOKE UC NO. 107 (Moh. Kamboh Pura)",
    "KAMOKE UC NO. 108 (Moh. Fatima Colony)",
    "KAMOKE UC NO. 109 (Moh. Usman Pura)",
    "KAMOKE UC NO. 110 (Moh. Kotli Bheeka)",
    "KAMOKE UC NO. 111 (Moh. Muslim Town)",
    "KAMOKE UC NO. 112 (Moh. Noor Pura)",
    "KAMOKE UC NO. 113 (Moh. Chah Dholi)",
    "KAMOKE UC NO. 114 (Moh. Sardar Pura)",
    "KAMOKE UC NO. 115 (Moh. Rasool Nagar)",
    "KAMOKE UC NO. 116 (Moh. Taj Colony)",
    "KAMOKE UC NO. 117 (Moh. Muslim Town)",
    "KAMOKE UC NO. 118 (Moh. Ghalla Mandi)",
  ]
};

Map<String, dynamic> six = {
  "NA": 84,
  "Candidates": [
    "Azhar Qayum Nahra",
    "Ch. Zulfiqar Ali",
    "Ch Bilal Ejaz",
    "Aytzaz Ijaz",
    "Rab Nawaz Cheema",
    "Abid Sohail Virk",
    "Amir Ali Hussain Khan",
    "Qasim Ali",
    "Muhammad Ishaq Khan",
    "Muhammad Islam",
    "Muhammad Asghar",
    "Muhammad Muhibb Uddeen"
  ],
  "Party": [
    "PMLN",
    "PPPP",
    "PTI",
    "Independent",
    "Independent",
    "AOAT",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "Independent",
    "TLP"
  ],
  "Areas": [
    "ABBDULLAH PUR",
    "ABIDABAD",
    "ALLAH DITTA",
    "ARGAN",
    "AUDHO RAI (QILA NOHID SINGH)",
    "AULAKH BHAIKE",
    "BABBAR",
    "BADDO RATTA",
    "BADDOKE",
    "BAHMANIAN",
    "BAKHSHISH PURA",
    "BALLOKI",
    "BARI WALA",
    "BATH",
    "BAWRE PIARA",
    "BEIG PUR",
    "BHADDAR",
    "BHADE",
    "BHAN PUR",
    "BHANGWAN",
    "BHARAIAN",
    "Bhiri Kalan",
    "Bhiri Khurd",
    "BHUND",
    "BOGA",
    "BOPRA KALAN",
    "BOPRA KHURD",
    "BUDHA CHANDU",
    "BUDHA GORAYA",
    "CHABBA SANDHWAN",
    "CHACHOKE",
    "CHADIALA KALAN",
    "CHAK AYAH",
    "CHAK BAHLOL",
    "CHAK CHATHA",
    "CHAK CHOHAR",
    "CHAK DUNI CHAND",
    "CHAK GHOSIA",
    "CHAK MARALI",
    "CHAK PAKHAR",
    "CHAK RAJADA",
    "CHAK SADU",
    "CHAK UMAR",
    "CHAK VIRKAN",
    "CHANDANIAN",
    "CHANDHAR",
    "CHAUDHRI",
    "CHELEKE",
    "CHIAN WALI",
    "CHIANWALI",
    "DEHR VIRKAN",
    "DERA SHAH JAMAL",
    "DHALLA",
    "DHAPAI WASAKH SINGH",
    "DHARIWAL",
    "DHAROKE",
    "DHERAM KOT",
    "DHILANWALI",
    "DHILLU BASHA",
    "DIPEPUR",
    "DOBURJI",
    "DOGRAN WALA",
    "DOGRAN WALA MALIAN",
    "DUCHHA",
    "EMINABAD T.C. (MIRZA COLONY, BEROON DAMDAMA, CIRCULAR ROAD)",
    "EMINABAD T.C. (MOH. BHINDRIAN/MO H. KAKKY ZIAN)",
    "EMINABAD T.C. (MOH. GUJRAN, BEROON UNCHA KHOLA)",
    "EMINABAD T.C. (MOH. HUDAIBIA COLONY, MOH. RORI SAHIB)",
    "EMINABAD T.C. (MOH. ISLAMABAD, PUL WALA IDARA SHAMAL , MADINA HOSPITAL)",
    "EMINABAD T.C. (MOH. JINNAH COLONY, NAI ABADI TAIL PURA)",
    "EMINABAD T.C. (MOH. KHUDIAN, BEROON QAZI DARWAZA/SAID PURA SHARQI",
    "EMINABAD T.C. (MOH. NIKKI MANDI, UNCHA KHOLA/MOH. SAID PURA)",
    "EMINABAD T.C. (MOH. NIKKI MANDI/MOH. KACTCHEHRI)",
    "EMINABAD T.C. (TAJ CHOWK CHUNGI NO. 1, REHMAN COLONY)",
    "FATEH WALA",
    "FATEHKI",
    "GARMULA VIRKAN",
    "GHAIBI",
    "GHUMMAN WALA",
    "GODHA",
    "GOHRI",
    "GOPI RAI",
    "GORAYA",
    "HAMBOKE",
    "HARAR",
    "HARCHOKI",
    "HARDO KULLEWALA",
    "HARDO MUGHAL CHAK",
    "Hardo Udday",
    "HARDO UDDE",
    "HARLAN WALI KOT MAND",
    "HARPAL BHATTI",
    "Islam Pura BHADE",
    "JAGOWALA",
    "JAGOWALA(Dhondianwala)",
    "JAHLAN",
    "JAJOKE",
    "JHALIAN WALA",
    "JOGI WALA",
    "KAHLWAN",
    "KALSIAN",
    "KARIAL KALAN",
    "KARIAL KHURD",
    "KASSOKI",
    "KAULO WALA",
    "KHAN MUSLMAN",
    "KHAN PIARA",
    "KHARA",
    "KHARK",
    "KHAWASRA",
    "KHOKHRAN",
    "KHURD",
    "KIRAN WALI",
    "KOHLOWALA",
    "KOROTANA",
    "KOT ABDUL MALIK",
    "KOT BAQAR",
    "KOT BHANU SHAH",
    "KOT BHUTTA",
    "KOT CHAND",
    "KOT KARAM CHAND",
    "KOT LADHA",
    "KOT LAJJA RAM",
    "KOT LALA",
    "KOT MAITLA",
    "KOT MARI",
    "KOT NISAR",
    "KOT PURIAN",
    "KOT SHERA",
    "KOTLI MAHIL",
    "KOTLI MANO SINDHU",
    "KOTLI MANSU",
    "KOTLI SAIB SINGH",
    "KURALKE",
    "KURAR",
    "KUTHIALI",
    "LALA PUR",
    "LANDE SHARIF",
    "LANJ",
    "LAUNKE",
    "LIL",
    "LUDHAR MUSLIM",
    "MACHAR WALA",
    "MACHIAN",
    "MAHMUDPUR",
    "MAHNGI KHURD",
    "MAHNGI KALAN",
    "MAJEED PUR",
    "MALE DI CHANDNI",
    "MANAK",
    "MANAKI",
    "MANDI QILA AHMAD ABAD",
    "MANDI SAYYIDAN",
    "MANDI SHER MUHAMMAD",
    "MANDIAN WALI",
    "MANDIAN WALI PATTI",
    "MANDIAR",
    "MANGAT",
    "MANGAT KALAN",
    "MANGAT KHURD",
    "MANZOOR PUR",
    "MAUZA CHHIB RANGERS",
    "MAUZA MELA",
    "MAZARIAN",
    "MERA SINGH",
    "MERKA",
    "MOHANA",
    "MOMAN PUR",
    "MOOCHI GUJJAR",
    "MUJAHID ABAD",
    "MUMTAZ PUR",
    "MURID PUR",
    "NAAKKA KALAN",
    "NAAKKA KHURD",
    "NADANA",
    "NAHR RANJHA",
    "NAIKO GHOUS PURA",
    "NARA",
    "NARANG PUR",
    "NAROWAL",
    "NATHA PUR",
    "NOU DERA",
    "NUR PUR",
    "NUR PUR RATA",
    "PHULARWAN",
    "PHULRAJAN",
    "PIRAO",
    "PREEM PUR",
    "PURA",
    "RADA DERA",
    "RADI",
    "RAJOWAL",
    "RANGLA",
    "RASOOL PUR",
    "RATTA WALI",
    "ROBERA",
    "ROHDARI",
    "ROKAN",
    "ROKU CHATTI",
    "SAID PUR",
    "SAKKA KALAN",
    "SAKKA KHURD",
    "SALMAN KAYA",
    "SALOWALI",
    "SANDHU NOSHAHRA",
    "SANDHU NOYAN",
    "SANDHU SAYADAN",
    "SARAI ALAMGIR",
    "SAROKE",
    "SERE GONDAL",
    "SERE JAGIR",
    "SERE MUSLIM",
    "SHADI WALI",
    "SHAH JAWAN",
    "SHAH KATRA",
    "SHAH KHAN",
    "SHAHDAD",
    "SHAHPUR",
    "SHAKKAR KOT",
    "SHAKOOR ABAD",
    "SHAKOOR ABAD",
    "SHAKOOR SHAH",
    "SHALAMAR",
    "SHAMASABAD",
    "SHANGLA WALI",
    "SHARAQ PUR",
    "SHERGARH",
    "SHERPUR",
    "SHERWAN",
    "SIDHU NATHA SINGH",
    "SIDHU NATHA SINGH",
    "SIKA WALI",
    "SILAN WALA",
    "SIRANWALI",
    "SUCHAN KOT",
    "SUIKHAR",
    "SUJAN WALA",
    "SULEWALA",
    "SULLE HARIS",
    "TAHKA",
    "TALWARA",
    "TANGA",
    "TARU",
    "TATRAL",
    "THAKAR",
    "THAKAR WALA",
    "THALIAN",
    "TIBI",
    "TITRON",
    "TOMARAJ",
    "UMARKE",
    "UMER KOT",
    "UMRAO WALI",
    "UNCHA MANDA",
    "UNCHA MANDI",
    "VADIYAN",
    "VEHARI VIRKAN",
    "WARA DARNA",
    "WARA NOOR DIN",
    "WARA SHERA",
    "WARO DARNA",
    "WARSI KALAN",
    "WARSI KHURD",
    "YARO KE",
    "YOUSAFWALA",
    "ZABARUWALA",
    "ZAFAR WALA",
    "ZAHID PUR",
    "ZAHID WALI",
    "ZAKIR WALI",
    "ZAMAIDA",
    "ZANGI ABAD",
    "ZANGI KE",
    "ZIRANDO",
    "ZULIFQAR PUR"
  ],
};
